# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23fecb4bc4e4f0ed0b4ed6a7daa3642d1e11a197aa724d6454762412a08c3c3ffac96a84c4c1616a82587a64cde3afa96b4edf53f3423e185f9e4211881f846

test:
  secret_key_base: 2057c01604b9957c1094b325846067d53fc90c80e4989741cad7a81577bd257cba78b3abe3bb96dcec22eb7ffc98b6bce4d9dc6bd968452befd6467cbdeda1a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
